-- GENERATED by tools/seed-sql.mjs from examples/*.json — do not edit by hand.
-- Regenerate: npm run seed:sql

insert into users (id, org_id, email) values
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'owner@example.com')
on conflict (id) do nothing;

-- ── Loan file completeness (loan_file.json) ────────────────────────
insert into process_maps (id, org_id, title, status) values
  ('10000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', 'Loan file completeness', 'draft')
on conflict (id) do nothing;

insert into nodes (map_id, id, primitive, label, config, x, y) values
  ('10000000-0000-0000-0000-000000000003', 'ch_intake', 'channel', 'Underwriting inbox', '{"tool":"composio.gmail","match":{"subject_patterns":["Loan file","Borrower documents"]},"describes":"Borrowers and brokers email documents to the underwriting inbox."}'::jsonb, 40, 180),
  ('10000000-0000-0000-0000-000000000003', 'doc_app', 'artifact', 'Application', '{"identity_key":"loan_number","fields":["loan_number","borrower_name","stated_income"],"source_hint":"the form headed ''Uniform Residential Loan Application''","describes":"The loan application form the borrower filled in."}'::jsonb, 280, 100),
  ('10000000-0000-0000-0000-000000000003', 'doc_stub', 'artifact', 'Pay stub', '{"identity_key":"loan_number","fields":["loan_number","employer","gross_pay"],"source_hint":"the payroll document with an employer name and a pay period","describes":"A pay stub proving the income on the application."}'::jsonb, 280, 300),
  ('10000000-0000-0000-0000-000000000003', 'rule_stub', 'policy', 'Application has a pay stub', '{"describes":"Every application on file needs a matching pay stub.","check":{"relation":"exists_matching","params":{"on":"loan_number"}},"reads":["doc_app.loan_number","doc_stub.loan_number"],"verdict_on":"doc_app","on_fail":"flag_and_continue","on_absent":"fail","confirmed_by":"c_02"}'::jsonb, 560, 260),
  ('10000000-0000-0000-0000-000000000003', 'rule_income', 'policy', 'Income is stated', '{"describes":"The borrower has to have put an income on the application.","check":{"relation":"present"},"reads":["doc_app.stated_income"],"verdict_on":"doc_app","on_fail":"flag_and_continue","on_absent":"fail","confirmed_by":"c_03"}'::jsonb, 560, 80),
  ('10000000-0000-0000-0000-000000000003', 'out_file', 'output', 'File review result', '{"rows":[{"label":"files_reviewed","fn":"count","of":"doc_app"},{"label":"files_complete","fn":"count","of":"doc_app","where":"pass"},{"label":"files_incomplete","fn":"count","of":"doc_app","where":"fail"},{"label":"incomplete_ids","fn":"list","of":"doc_app.loan_number","where":"fail"}],"describes":"How many files we reviewed and which are still incomplete."}'::jsonb, 820, 160)
on conflict (map_id, id) do nothing;

insert into edges (map_id, id, from_node, to_node, config) values
  ('10000000-0000-0000-0000-000000000003', 'l1', 'ch_intake', 'doc_app', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l2', 'ch_intake', 'doc_stub', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l3', 'doc_app', 'doc_stub', '{"rel":"pairs_with","on":"loan_number"}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l4', 'doc_app', 'rule_stub', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l5', 'doc_stub', 'rule_stub', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l6', 'doc_app', 'rule_income', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l7', 'rule_stub', 'out_file', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000003', 'l8', 'rule_income', 'out_file', '{}'::jsonb)
on conflict (map_id, id) do nothing;

-- ── Inbound import receiving (receiving.json) ──────────────────────
insert into process_maps (id, org_id, title, status) values
  ('10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Inbound import receiving', 'draft')
on conflict (id) do nothing;

insert into nodes (map_id, id, primitive, label, config, x, y) values
  ('10000000-0000-0000-0000-000000000002', 'ch_a1', 'channel', 'Pre-alert inbox', '{"tool":"composio.gmail","match":{"subject_patterns":["Pre-Alert Documents"]},"describes":"Freight forwarders email us the paperwork before a container lands."}'::jsonb, 40, 200),
  ('10000000-0000-0000-0000-000000000002', 'rec_inv', 'artifact', 'Commercial invoice', '{"identity_key":"invoice_number","fields":["invoice_number","container_no"],"source_hint":"attachment headed ''Commercial Invoice''","describes":"The commercial invoice for a shipment. It comes in as an attachment on the pre-alert."}'::jsonb, 260, 120),
  ('10000000-0000-0000-0000-000000000002', 'rec_good', 'artifact', 'Good', '{"fields":["hts","fda_product_code","anda","reg_no","ndc"],"describes":"A line item on the invoice — one product, with its regulatory codes."}'::jsonb, 480, 40),
  ('10000000-0000-0000-0000-000000000002', 'rec_batch', 'artifact', 'Batch', '{"identity_key":"batch_number","fields":["batch_number"],"describes":"A manufacturing batch listed against a line item."}'::jsonb, 480, 200),
  ('10000000-0000-0000-0000-000000000002', 'rec_coa', 'artifact', 'Certificate of analysis', '{"identity_key":"batch_number","fields":["batch_number"],"source_hint":"attachment headed ''Certificate of Analysis''","describes":"The lab certificate for a batch, attached to the same email."}'::jsonb, 480, 320),
  ('10000000-0000-0000-0000-000000000002', 'rule_fields', 'policy', 'Required codes present', '{"describes":"Each good has to carry all five regulatory codes.","check":{"relation":"present"},"reads":["rec_good.hts","rec_good.fda_product_code","rec_good.anda","rec_good.reg_no","rec_good.ndc"],"verdict_on":"rec_good","on_fail":"flag_and_continue","on_absent":"fail","confirmed_by":"c_04"}'::jsonb, 720, 40),
  ('10000000-0000-0000-0000-000000000002', 'rule_coa', 'policy', 'Batch has certificate', '{"describes":"Every batch on the invoice needs a certificate of analysis.","check":{"relation":"exists_matching","params":{"on":"batch_number"}},"reads":["rec_batch.batch_number","rec_coa.batch_number"],"verdict_on":"rec_batch","on_fail":"flag_and_continue","on_absent":"fail","confirmed_by":"c_07"}'::jsonb, 720, 260),
  ('10000000-0000-0000-0000-000000000002', 'ch_out', 'channel', 'Discrepancy email', '{"tool":"composio.gmail","request":{"to":"danieljhsiao@gmail.com","subject":"Discrepancy — invoice {rec_inv.invoice_number}","body":"Missing certificates for: {rec_batch.batch_number where fail}"},"describes":"We email the forwarder about anything missing and wait for them to send it."}'::jsonb, 960, 380),
  ('10000000-0000-0000-0000-000000000002', 'out_res', 'output', 'Shipment result', '{"rows":[{"label":"invoices_processed","fn":"count","of":"rec_inv"},{"label":"invoices_failed","fn":"count","of":"rec_inv","where":"fail"},{"label":"goods_failed","fn":"count","of":"rec_good","where":"fail"},{"label":"batches_processed","fn":"count","of":"rec_batch"},{"label":"batches_failed","fn":"count","of":"rec_batch","where":"fail"},{"label":"failed_batch_ids","fn":"list","of":"rec_batch.batch_number","where":"fail"}],"describes":"How many invoices and batches we processed, and which ones failed."}'::jsonb, 960, 140)
on conflict (map_id, id) do nothing;

insert into edges (map_id, id, from_node, to_node, config) values
  ('10000000-0000-0000-0000-000000000002', 'e1', 'ch_a1', 'rec_inv', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e2', 'ch_a1', 'rec_coa', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e3', 'rec_inv', 'rec_good', '{"rel":"contains","cardinality":"many","on_child_fail":"ignore"}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e4', 'rec_inv', 'rec_batch', '{"rel":"contains","cardinality":"many","on_child_fail":"ignore"}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e5', 'rec_batch', 'rec_coa', '{"rel":"pairs_with","on":"batch_number"}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e6', 'rec_good', 'rule_fields', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e7', 'rec_batch', 'rule_coa', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e8', 'rec_coa', 'rule_coa', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e9', 'rule_fields', 'out_res', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e10', 'rule_coa', 'out_res', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000002', 'e11', 'rule_coa', 'ch_out', '{"on":"fail","await":{"channel":"ch_a1","correlate_on":"invoice_number"},"rescope":["rec_batch"],"max_attempts":3,"timeout":"PT30S","on_exhausted":"continue"}'::jsonb)
on conflict (map_id, id) do nothing;

-- ── Inbound import receiving (draft) (receiving_draft.json) ──────────────
insert into process_maps (id, org_id, title, status) values
  ('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Inbound import receiving (draft)', 'draft')
on conflict (id) do nothing;

insert into nodes (map_id, id, primitive, label, config, x, y) values
  ('10000000-0000-0000-0000-000000000001', 'ch_a1', 'channel', 'Pre-alert inbox', '{"tool":"composio.gmail","match":{"subject_patterns":["Pre-Alert Documents"]},"describes":"Freight forwarders email us the paperwork before a container lands."}'::jsonb, 40, 200),
  ('10000000-0000-0000-0000-000000000001', 'ch_a2', 'channel', 'Forwarder resend', '{"tool":"composio.gmail","match":{"subject_patterns":["FW: Pre-Alert"]},"describes":"Sometimes the forwarder resends the same paperwork from a different address."}'::jsonb, 40, 360),
  ('10000000-0000-0000-0000-000000000001', 'rec_inv', 'artifact', 'Commercial invoice', '{"fields":["invoice_number","container_no"],"describes":"The commercial invoice for a shipment."}'::jsonb, 260, 260),
  ('10000000-0000-0000-0000-000000000001', 'rec_good', 'artifact', 'Good', '{"describes":"A line item on the invoice."}'::jsonb, 460, 60),
  ('10000000-0000-0000-0000-000000000001', 'a_hts', 'artifact', 'HTS', '{}'::jsonb, 660, -40),
  ('10000000-0000-0000-0000-000000000001', 'a_fda', 'artifact', 'FDA product code', '{}'::jsonb, 660, 20),
  ('10000000-0000-0000-0000-000000000001', 'a_anda', 'artifact', 'ANDA', '{}'::jsonb, 660, 80),
  ('10000000-0000-0000-0000-000000000001', 'a_reg', 'artifact', 'Reg No', '{}'::jsonb, 660, 140),
  ('10000000-0000-0000-0000-000000000001', 'a_ndc', 'artifact', 'NDC', '{}'::jsonb, 660, 200),
  ('10000000-0000-0000-0000-000000000001', 'rec_batch', 'artifact', 'Batch', '{"identity_key":"batch_number","fields":["batch_number"],"describes":"A manufacturing batch listed against a line item."}'::jsonb, 460, 300),
  ('10000000-0000-0000-0000-000000000001', 'rec_coa', 'artifact', 'Certificate of analysis', '{"identity_key":"batch_number","fields":["batch_number"],"describes":"The lab certificate for a batch."}'::jsonb, 460, 420),
  ('10000000-0000-0000-0000-000000000001', 'rule_fields', 'policy', 'Required codes present', '{"describes":"Each good has to carry all its regulatory codes.","on_fail":"flag_and_continue","on_absent":"fail"}'::jsonb, 900, 80),
  ('10000000-0000-0000-0000-000000000001', 'rule_coa', 'policy', 'Batch has certificate', '{"describes":"Chase up missing certificates — every batch needs one.","on_fail":"flag_and_continue","on_absent":"fail"}'::jsonb, 900, 360),
  ('10000000-0000-0000-0000-000000000001', 'out_res', 'output', 'Shipment result', '{"rows":[{"label":"invoices_processed","fn":"count","of":"rec_inv"},{"label":"batches_failed","fn":"count","of":"rec_batch","where":"fail"}],"describes":"How many invoices we processed and which batches failed."}'::jsonb, 1140, 220)
on conflict (map_id, id) do nothing;

insert into edges (map_id, id, from_node, to_node, config) values
  ('10000000-0000-0000-0000-000000000001', 'd1', 'ch_a1', 'rec_inv', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd2', 'ch_a2', 'rec_inv', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd3', 'ch_a1', 'rec_coa', '{"cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd4', 'rec_inv', 'rec_good', '{"rel":"contains","cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd5', 'rec_inv', 'rec_batch', '{"rel":"contains","cardinality":"many"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd6', 'rec_good', 'a_hts', '{"rel":"contains"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd7', 'rec_good', 'a_fda', '{"rel":"contains"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd8', 'rec_good', 'a_anda', '{"rel":"contains"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd9', 'rec_good', 'a_reg', '{"rel":"contains"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd10', 'rec_good', 'a_ndc', '{"rel":"contains"}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd11', 'a_hts', 'rule_fields', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd12', 'a_fda', 'rule_fields', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd13', 'a_anda', 'rule_fields', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd14', 'a_reg', 'rule_fields', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd15', 'a_ndc', 'rule_fields', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd16', 'rec_batch', 'rule_coa', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd17', 'rec_coa', 'rule_coa', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd18', 'rule_fields', 'out_res', '{}'::jsonb),
  ('10000000-0000-0000-0000-000000000001', 'd19', 'rule_coa', 'out_res', '{}'::jsonb)
on conflict (map_id, id) do nothing;

