-- GENERATED by tools/seed-sql.mjs from examples/*.json — do not edit by hand.
-- Regenerate: npm run seed:sql

insert into users (id, org_id, email) values
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'owner@example.com')
on conflict (id) do nothing;

