#!/usr/bin/env node
// Generates supabase/seed.sql from examples/*.json.
//
// The boards live in the database, because the database is the bus — the
// canvas, the review worker and the CLI all coordinate through rows and none
// of them calls another directly. examples/ stays the source of truth on disk
// so the boards are reviewable in a diff; this turns them into rows.
//
// Regenerate with: npm run seed:sql

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath, not .pathname: .pathname percent-encodes, so any space in the
// checkout path silently yields a directory that does not exist.
const ROOT = fileURLToPath(new URL("..", import.meta.url));
const EXAMPLES = join(ROOT, "examples");
const OUT = join(ROOT, "supabase", "seed.sql");

// Fixed ids so re-seeding is idempotent and URLs stay stable across resets.
const ORG_ID = "00000000-0000-0000-0000-000000000001";
const USER_ID = "00000000-0000-0000-0000-000000000002";
const MAP_IDS = {
  receiving_draft: "10000000-0000-0000-0000-000000000001",
  receiving: "10000000-0000-0000-0000-000000000002",
  loan_file: "10000000-0000-0000-0000-000000000003",
};

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;

const parts = [
  `-- GENERATED by tools/seed-sql.mjs from examples/*.json — do not edit by hand.`,
  `-- Regenerate: npm run seed:sql`,
  ``,
  `insert into users (id, org_id, email) values`,
  `  ('${USER_ID}', '${ORG_ID}', 'owner@example.com')`,
  `on conflict (id) do nothing;`,
  ``,
];

// The UI opens on an empty workspace by default. Pass --examples to load the
// example boards as rows — useful for demoing the review loop against the
// deliberately-messy draft, but never the default: "there is no SOP" is the
// premise, and starting on three prefilled boards argues against it.
const withExamples = process.argv.includes("--examples");
const files = withExamples
  ? readdirSync(EXAMPLES).filter((f) => f.endsWith(".json")).sort()
  : [];

for (const file of files) {
  const slug = file.replace(/\.json$/, "");
  const mapId = MAP_IDS[slug];
  if (!mapId) {
    console.error(`seed-sql: no fixed uuid for "${slug}" — add one to MAP_IDS.`);
    process.exit(1);
  }

  const raw = JSON.parse(readFileSync(join(EXAMPLES, file), "utf8"));
  const title = raw.title ?? slug;

  parts.push(`-- ── ${title} (${file}) ${"─".repeat(Math.max(0, 46 - title.length))}`);
  parts.push(`insert into process_maps (id, org_id, title, status) values`);
  parts.push(`  ('${mapId}', '${ORG_ID}', ${q(title)}, 'draft')`);
  parts.push(`on conflict (id) do nothing;`);
  parts.push(``);

  parts.push(`insert into nodes (map_id, id, primitive, label, config, x, y) values`);
  parts.push(
    raw.nodes
      .map(
        (n) =>
          `  ('${mapId}', ${q(n.id)}, ${q(n.primitive)}, ${q(n.label)}, ${j(n.config ?? {})}, ${n.x ?? 0}, ${n.y ?? 0})`,
      )
      .join(",\n") + `\non conflict (map_id, id) do nothing;`,
  );
  parts.push(``);

  parts.push(`insert into edges (map_id, id, from_node, to_node, config) values`);
  parts.push(
    raw.edges
      .map(
        (e) =>
          `  ('${mapId}', ${q(e.id)}, ${q(e.from)}, ${q(e.to)}, ${j(e.config ?? {})})`,
      )
      .join(",\n") + `\non conflict (map_id, id) do nothing;`,
  );
  parts.push(``);
}

writeFileSync(OUT, parts.join("\n") + "\n");
console.log(
  files.length === 0
    ? "seed-sql: wrote an empty workspace to supabase/seed.sql (pass --examples for the sample boards)"
    : `seed-sql: wrote ${files.length} board${files.length === 1 ? "" : "s"} to supabase/seed.sql`,
);
for (const f of files) console.log(`  ${f.replace(/\.json$/, "")} -> ${MAP_IDS[f.replace(/\.json$/, "")]}`);
