#!/usr/bin/env bash
# Regenerates .env.local from the running Supabase stack.
#
# Emits EXACTLY the keys in .env.example, in the same order and the same
# unquoted format — the example is a template, so it has to be truthful about
# the shape. `supabase status -o env` also prints JWT_SECRET, MAILPIT_URL, the
# S3 credentials and a handful of other URLs; this app uses none of them, so
# they are dropped rather than carried around as noise.
#
# Values go from the CLI straight to disk — never through a terminal or a
# clipboard. Anything you filled in by hand is preserved.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! supabase status >/dev/null 2>&1; then
  echo "The Supabase stack isn't running. Start it first:" >&2
  echo "  supabase start" >&2
  exit 1
fi

STATUS="$(supabase status -o env)"

# `supabase status -o env` quotes its values; .env.example doesn't. Strip.
from_status() {
  echo "$STATUS" | grep "^$1=" | head -1 | cut -d= -f2- | sed 's/^"//; s/"$//'
}

# Preserve anything already set by hand — API keys we can't generate.
keep() {
  local name="$1" default="${2:-}"
  if [ -f .env.local ] && grep -q "^${name}=" .env.local; then
    grep "^${name}=" .env.local | head -1 | cut -d= -f2-
  else
    echo "${default}"
  fi
}

umask 077
{
  echo "# Generated by: npm run env:local"
  echo "# Same keys, order and format as .env.example."
  echo "# Supabase values come from the running stack; the rest are preserved."
  echo ""
  echo "# ── Supabase ───────────────────────────────────────────────────────────"
  echo "NEXT_PUBLIC_SUPABASE_URL=$(from_status API_URL)"
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$(from_status ANON_KEY)"
  echo "SUPABASE_SERVICE_ROLE_KEY=$(from_status SERVICE_ROLE_KEY)"
  echo "DATABASE_URL=$(from_status DB_URL)"
  echo ""
  echo "# ── Anthropic ──────────────────────────────────────────────────────────"
  echo "ANTHROPIC_API_KEY=$(keep ANTHROPIC_API_KEY)"
  echo "ANTHROPIC_MODEL=$(keep ANTHROPIC_MODEL claude-sonnet-5)"
  echo ""
  echo "# ── Composio ───────────────────────────────────────────────────────────"
  echo "COMPOSIO_API_KEY=$(keep COMPOSIO_API_KEY)"
  echo "COMPOSIO_USER_ID=$(keep COMPOSIO_USER_ID)"
  echo "COMPOSIO_GMAIL_CONNECTION_ID=$(keep COMPOSIO_GMAIL_CONNECTION_ID)"
  echo ""
  echo "# ── Temporal ───────────────────────────────────────────────────────────"
  echo "TEMPORAL_ADDRESS=$(keep TEMPORAL_ADDRESS localhost:7233)"
  echo "TEMPORAL_NAMESPACE=$(keep TEMPORAL_NAMESPACE default)"
  echo "TEMPORAL_TASK_QUEUE=$(keep TEMPORAL_TASK_QUEUE workflow-engine)"
  echo ""
  echo "# ── Run mode ───────────────────────────────────────────────────────────"
  echo "CHANNEL_MODE=$(keep CHANNEL_MODE capture)"
} > .env.local.tmp

mv .env.local.tmp .env.local
chmod 600 .env.local

echo "wrote .env.local (mode 600, gitignored)"
echo "run 'npm run doctor' to check it end to end"
